=head1 NAME

    vee-reindex

=head1 SYNOPSIS

    vee-reindex [-d|-h]

=head1 OPTIONS 

=over 4

=item -d direcory

Specify directory inwhich to locate the I<.vee> directory, which contains the
I<*.raw> files.

=item -h 

Show usage

=back

=head1 DESCRIPTION

C<vee-reindex> is a part of the I<vee> family of utilities that is used for
rebuilding the index based on the I<*.raw> contents of I<.vee>.

It is provided as a basic utility required to build tools to manage I<vee>
posts.

=head1 EXAMPLE

    vee-rebuild -d $HOME/public_html

=head1 BUGS 

Please report them to L<https://github.com/estrabd/vee/issues>
