=head1 NAME

    veecat

=head1 SYNOPSIS

    echo file.raw | veecat

B<Note: in order to make it easier to write scripts, the I<*.raw> file name is
passed in via STDIN.>

=head1 OPTIONS

=over 4

=item -a

Show the entire contents of the I<*.raw> file

=item -b

Show just the body contents

=item -d

Show just the value of the date field

=item -t

Show just the titla

=item -h

Show usage

=back

=head1 DESCRIPTION 

C<veecat> is a part of the I<vee> family of utilities that is useful for
extracting information from I<*.raw> files.

It is provided as a basic utility required to build tools to manage I<vee>
posts.

=head1 EXAMPLES 

The best example of all is to take a look at the I<vee-rebuild> tool.

Used in conjunction with I<veels>:

    for f in `veels`; 
    do
        TITLE=`echo $f | veecat -t`
        echo $TITLE
    done

=head1 BUGS AND LIMITATIONS

Currently, I<veecat> can't be used at the commandline as one would expect,
e.g.:

    veels | veecat -t

=head1 BUGS 

Please report them to L<https://github.com/estrabd/vee/issues>
