=head1 DEPRECATED

This utility is being deprecated before it even makes it into a release.

=head1 NAME

    veels

=head1 SYNOPSIS

    veels

=head1 OPTIONS 

=over 4

=item -d direcory

Specify directory inwhich to locate the I<.vee> directory, which contains the
I<*.raw> files.

=item -l 

Use I<ls> as found in PATH with default options

=item -L I<ls options>

Use I<ls> as found in PATH with provided options (must be valid I<ls> options)

=item -r

Sort oldest to newest

=item -x

Strip C<.raw> from file name; this is useful for also iterating over other
files that might share a name with the I<*.raw> file (e.g., I<*.html>).

=item -h

Usage output

=back

=head1 DESCRIPTION

C<veels> is a part of the I<vee> family of utilities that is useful for
iterating over I<*.raw> files.

It is provided as a basic utility required to build tools to manage I<vee>
posts.

=head1 EXAMPLES

The best example of all is to take a look at the I<vee-rebuild> tool.

    for f in `veels`; 
    do
        # do stuff with $f
    done

=head1 BUGS

Please report them to L<https://github.com/estrabd/vee/issues>

