.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH vee-rebuild 1 "June 2012" Vee "User Manuals"
.SH NAME
vee-rebuild \- a utility for rebuilding vee's index.html based on the contents of the $VEEDIR/.vee/*.raw files.
.SH SYNOPSIS
.B vee-rebuild [-d $VEEDIR/] > path/to/newindex.html 
.SH DESCRIPTION
.B vee-reindex (1)
script to rebuild index based on .raw files in $VEEDIR/.vee/ created out of necessity, but
also provides a good idea of how one can use
.B veels (1)
and
.B veecat (1)
to create a useful script. That it outputs
.I html
is of no consequence to the example. If another output format is desired, this
script can be used as a template or example.
.SH OPTIONS
.IP "-d publish_dir"
Specify the parent directory of
.I ./.vee
; defaults to the present working directory as known to 
.I `pwd`
like 
.B vee (1)
.SH FILES
none
.SH ENVIRONMENT
is not affected by any external files and is meant to produce a new 
.I html
index file. 
.SH DIAGNOSTICS
.SH BUGS
Please report at 
.I https://github.com/estrabd/vee/issues
.SH AUTHOR
B. Estrade <estrabd@gmail.com>
.SH "SEE ALSO"
.BR vee (1)
.BR veels (1)
.BR veecat (1)
