.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH vee 5 "June 2012" Vee "User Manuals"
.SH NAME
vee \- vee is a zero-conf, cli microblogging tool; does one thing, and does it well. 
This page describes all relevant files.
.SH FILES
.I .veerc 
.RS
The primary configuration file. See
.B veerc(5)
for more details about available options and how it affect 
.B vee(1)
's operation.
.RE
.I ./vee-bottom.tpl
.RS
The default bottom template file, assumed to be
.I html
.I ./vee-top.tpl
.RS
The default top template file, assumed to be
.I html
.RE
.I ./vee-pre
.RS
The default pre-hook.
.BR vee-hooks(5)
for further details about creating a hook.
.RE
.I ./index.html
.RS
The default index file.
.BR vee-index(5)
for further details.
.RE
.I *.raw
.RS
The raw source of all posts before being formatted by
.I fold
, etc.
See
.B vee-raw(5)
for more details about it's format and use.
.SH AUTHOR
B. Estrade <estrabd@gmail.com>
.SH "SEE ALSO"
.BR veerc(5)
.BR vee-index(5)
.BR vee-hooks(5)
.BR vee-raw(5)
.BR vee-templates(5)
